server:
  port: 8081
spring:
  application:
    name: week1

#自定义配置
my:
  mood:
    today: 周五
    content: 期待周末
    author: "小程序员"

#功能开关
  feature:
    helloSwitch: true #true=开放接口，false=关闭接口
    closeMsg: "该接口正在维护，十分钟后再来吧"

tbz:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c4019917b8da661dbd
      accountToken: 2d6805262ad2420ab7b49e0ee9d9c633
      appId: 2c94811c9860a9c4019917b8dbc81dc4
      templateId: 1